# Generated by Django 4.0 on 2021-12-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('For rent', 'for rent'), ('For sale', 'for sale')], max_length=20)),
                ('lesae_duration', models.CharField(choices=[('Min', 'min'), ('Max', 'max')], max_length=50)),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Studio', 'Studio'), ('Store', 'Store'), ('Vila', 'Vila')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('area', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('Weekly', 'weekly'), ('Monthly', 'monthly'), ('Yearly', 'yearly')], max_length=50)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('advanced_price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('available_until', models.DateField(blank=True, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.city')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('gander', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=100)),
                ('brith_date', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('user_type', models.CharField(choices=[('Admin', 'admin'), ('Partiner', 'partiner'), ('User', 'user')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.country')),
            ],
        ),
        migrations.CreateModel(
            name='Property_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_defult_image', models.BooleanField(default=False, verbose_name='Defult_Image')),
                ('image', models.ImageField(upload_to='')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.state'),
        ),
    ]
