# Generated by Django 4.0 on 2021-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('For rent', 'For rent'), ('For sale', 'For sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='lesae_duration',
            field=models.CharField(choices=[('Min', 'Min'), ('Max', 'Max')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gander',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Partiner', 'Partiner'), ('User', 'User')], max_length=30),
        ),
    ]
